<form style="margin-top: 70px;" method="post" action="/index/update?id=<?php echo $data->_id?>">
  <div class="form-row" >
    <div class="form-group col-md-6">
      <label for="inputEmail4">Name</label>
      <input type="text" class="form-control" value="<?php echo $data->name ?>" name="name" placeholder="Name">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Category Name</label>
      <input type="text" class="form-control" value="<?php echo $data->category ?>"
      name="category" placeholder="Category">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Price</label>
      <input type="number" class="form-control" value="<?php echo $data->price ?>" name="price" placeholder="Price">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Stock</label>
      <input type="number" class="form-control" value="<?php echo $data->stock ?>" name="stock" placeholder="Stock">
    </div>
  </div>
  <button type="submit" class="btn btn-success">Update</button>
</form>