<?php
include_once APP_PATH . "/views/header.phtml";
?>
<form style="margin-top: 70px;" method="post" action="/index/add">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Name</label>
      <input type="text" class="form-control" name="name" placeholder="Name">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Category Name</label>
      <input type="text" class="form-control" name="category" placeholder="Category">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Price</label>
      <input type="number" class="form-control" name="price" placeholder="Price">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Stock</label>
      <input type="number" class="form-control" name="stock" placeholder="Stock">
    </div>
  </div>

  <div id='meta'>
    Meta Details
    <div id="meta-rows" class='m-1'>
      <div class="meta-row">
        <input type="text" placeholder="Filed" name='m_field[]'>
        <input type="text" placeholder="Value" name='m_value[]'>
        <input class="btn btn-primary" type="button" id="addMeta" value="+">
        <input class="btn btn-primary" type="button" id="removeMeta" value="-">
      </div>
    </div>
  </div>
  <div id='variation'>
    Other Variations
    <div id="variation-rows" class='m-1'>
      <div class="variation-row">
        <input type="text" placeholder="Field" name="v_field[]">
        <input type="text" placeholder="Value" name='v_value[]'>
        <input type="text" placeholder="Price" name='v_price[]'>
        <input class="btn btn-primary" type="button" id="addVariation" value="+">
        <input class="btn btn-primary" type="button" id="removeVariation" value="-">
      </div>
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>