<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top bg-light navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#"
      >NavBar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item">
          <a class="nav-link mx-2" href="/"><i class="fas fa-plus-circle pe-2"></i>Add Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="/index/display"><i class="fas fa-heart pe-2"></i>Display Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="/order"><i class="fas fa-plus-circle pe-2"></i>Add Order</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="/order/display"><i class="fas fa-heart pe-2"></i>Display Order</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->